name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        neovim_version: [nightly, v0.12.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - run: nvim --version
      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/nvim-mini/mini.test \
            ~/.local/share/nvim/site/pack/core/opt/mini.test
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter-textobjects \
            ~/.local/share/nvim/site/pack/core/opt/nvim-treesitter-textobjects
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter \
            ~/.local/share/nvim/site/pack/core/opt/nvim-treesitter
      - uses: tree-sitter/setup-action/cli@v2
      - name: Install treesitter parsers
        run: |
          nvim --headless --noplugin -u scripts/minimal_init.lua \
            -c "lua vim.cmd('packadd nvim-treesitter'); require('nvim-treesitter').install({ 'cpp', 'bash', 'markdown', 'html' }):wait(600000)" \
            -c "qa!"
      - run: make test
